### ISSUE TITLE
texturize enhance: pic should be PIL Image or ndarray

### ISSUE THREAD

**Issue by terrainer** [texturedesign/texturize#47]
Full traceback:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\tools\miniconda3\envs\texturize\Scripts\texturize.exe\__main__.py", line 7, in <module>
  File "C:\tools\miniconda3\envs\texturize\Lib\site-packages\texturize\__main__.py", line 154, in main
    cmd = commands.Enhance(target_arr, source_arr, zoom=zoom)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\texturize\Lib\site-packages\texturize\commands.py", line 105, in __init__
    self.target = load_tensor_from_image(target, device="cpu")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\texturize\Lib\site-packages\texturize\io.py", line 58, in load_tensor_from_image
    return V.to_tensor(image).unsqueeze(0).to(device, dtype)
           ^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\texturize\Lib\site-packages\torchvision\transforms\functional.py", line 140, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'tuple'>`

Getting this when trying to use the enhance command with two RGB, 8 bits-per-channel, PNG files. Unsure what I'm doing wrong.
Command used: `texturize enhance tests/lowres.png with tests/highres.png --zoom=4`

**Comment by POD666** [comment]
Just got the same issue:
```
$ texturize remake sample.jpg like sample2.jpg --weight 0.5 -o test.jpg
...
pic should be PIL Image or ndarray. Got <class 'tuple'>
```

**Comment by htoyryla** [comment]
I get the same error and it persists regardless of which PyTorch & torchvision version is in use.

However, I have used texturize successfully two years ago. I still have the env I used then and it works (texturize version 0.12). 

So you could try to install that
```
pip install texturize==0.12
```
and see if it works. It is not the latest version though.

**Comment by htoyryla** [comment]
Seems to me that the errors result as follows

First the source and the target are extracted from the command line here https://github.com/texturedesign/texturize/blob/637a2135c9b18a3848202e5e25dd0823780592c7/src/texturize/__main__.py#L141-L142 

using this function https://github.com/texturedesign/texturize/blob/637a2135c9b18a3848202e5e25dd0823780592c7/src/texturize/io.py#L15-L26 which returns a tuple (a tensor, a list of props). For the source, these are saved in separate variables, but the target the tuple is stored.  

In Remake https://github.com/texturedesign/texturize/blob/637a2135c9b18a3848202e5e25dd0823780592c7/src/texturize/commands.py#L120-L124 then this target is passed here https://github.com/texturedesign/texturize/blob/637a2135c9b18a3848202e5e25dd0823780592c7/src/texturize/io.py#L47-L59 where it checks if it is a tensor, it is not because it is tuple (tensor, list), and assuming it is a PIL image tries to convert it to a tensor which of course results in an error.

I have not tried to modify the code but a simple solution might be to modify this line https://github.com/texturedesign/texturize/blob/637a2135c9b18a3848202e5e25dd0823780592c7/src/texturize/__main__.py#L142

to this

```
target_arr, _ = io.load_tensor_from_files(target) if target else None
```

Edits: due to copy-paste errors the links to code were not correct in the original posting, now corrected.

**Comment by htoyryla** [comment]
Tried to test the change I proposed but not being familiar with poetry tool did not find a way to run my version.
